name: CI/CD Pipeline

on:
  # Trigger khi có push vào bất kỳ nhánh nào
  push:
    branches-ignore:
      - main  # Không trigger khi push trực tiếp vào main
  pull_request:
    branches: 
      - main  # Chỉ trigger khi có PR vào main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm install
        
      - name: Fix security vulnerabilities
        run: npm audit fix --force || true
        
      # Sau này khi có tests sẽ uncomment
      # - name: Run tests
      #   run: npm test

  push-to-dev:
    needs: build-and-test  # Chỉ chạy khi build-and-test thành công
    if: github.ref != 'refs/heads/main' && github.ref != 'refs/heads/dev'  # Chỉ chạy khi không phải push vào main hoặc dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Push to dev branch
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'github-actions@github.com'
          git fetch origin dev
          git checkout -b dev origin/dev
          git merge ${{ github.sha }} --no-ff -m "Merge changes from feature branch"
          git push origin dev

  create-pr-to-main:
    needs: [build-and-test, push-to-dev]  # Chỉ chạy khi cả hai job trước thành công
    if: github.ref == 'refs/heads/dev'  # Chỉ chạy khi có thay đổi trên nhánh dev
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Create Pull Request to main
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PAT_TOKEN }}
          base: main
          branch: dev
          title: 'Merge dev into main'
          body: |
            Automated pull request from dev to main
            All tests have passed and changes have been verified.
            
            Changes:
            ${{ github.event.head_commit.message }}
          draft: false
          delete-branch: false

  deploy-to-production:
    needs: [build-and-test]
    if: github.ref == 'refs/heads/main'  # Chỉ deploy khi merge vào main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm install
        
      - name: Deploy to Production
        env:
          NODE_ENV: production
        run: |
          echo "Deploying to production..."
          # Thêm các lệnh deploy production ở đây 